/* 将图标名映射为更具语义化的名称 */
export const iconMap = {
  plus: 'icon-plus',
  swapLeft: 'icon-swap-left',
  swapRight: 'icon-swap-right',
  search: 'icon-search',
  zoomIn: 'icon-zoomin',
  zoomOut: 'icon-zoomout',
  close: 'icon-close',
  ellipsis: 'icon-ellipsis',
  list: 'icon-unorderedlist',
  menu: 'icon-menu',
  down: 'icon-down',
  up: 'icon-up',
  left: 'icon-left',
  right: 'icon-right',
  tag: 'icon-tag',
  image: 'icon-image',
  bell: 'icon-bell',
  delete: 'icon-delete',
  location: 'icon-location',
  setting: 'icon-setting',
  redo: 'icon-redo',
  undo: 'icon-undo',
  sync: 'icon-sync',
  warn: 'icon-warning-circle',
  question: 'icon-question-circle',
  increase: 'icon-plus-circle',
  decrease: 'icon-minus-circle',
  info: 'icon-info-circle',
  error: 'icon-close-circle',
  success: 'icon-check-circle',
};

export const svgIconMap = {
  success: 'icon-result_success',
  error: 'icon-result_error',
  warning: 'icon-result_warn',
  waiting: 'icon-dengdaoshenhe',
  notFound: 'icon-icon-test2',
  serverError: 'icon-icon-test3',
  notAuth: 'icon-icon-test1',
  empty: 'icon-empty',
};
