export const dataSource2 = [
  {
    id: '55794644',
    name: '主宰者 许珀里翁',
    jName: 'マスター・ヒュペリオン',
    meta: {
      race: '天使',
      property: '光',
      level: '8',
    },
    atk: '2700',
    def: '2100',
    pkg: ['SD20'],
  },
  {
    id: '59509952',
    name: '大天使 克里斯提亚',
    jName: '大天使クリスティア',
    meta: {
      race: '天使',
      property: '光',
      level: '8',
    },
    atk: '2800',
    def: '2300',
    pkg: ['SD20'],
  },
  {
    id: '64734921',
    name: '创造之代行者 维纳斯',
    jName: '創造の代行者 ヴィーナス',
    meta: {
      race: '天使',
      property: '光',
      level: '3',
    },
    atk: '1600',
    def: '0',
    pkg: ['EE02', '308', 'SD20'],
  },
  {
    id: '91188343',
    name: '神秘之代行者 厄斯',
    jName: '神秘の代行者 アース',
    meta: {
      race: '天使',
      property: '光',
      level: '2',
    },
    atk: '1000',
    def: '800',
    pkg: ['SD20'],
  },
  {
    id: '39552864',
    name: '神圣球体',
    eName: '神聖なる球体',
    meta: {
      race: '天使',
      property: '光',
      level: '2',
    },
    atk: '500',
    def: '500',
    pkg: ['EE02', '308', 'SD20'],
  },
  {
    id: '17266660',
    name: '朱光宣告者',
    jName: '朱光の宣告者',
    meta: {
      race: '天使',
      property: '光',
      level: '2',
    },
    atk: '300',
    def: '500',
    pkg: ['TDGS(601)', 'EXP02', 'TU07'],
  },
  {
    id: '37742478',
    name: '欧尼斯特',
    jName: 'オネスト',
    meta: {
      race: '天使',
      property: '光',
      level: '4',
    },
    atk: '1100',
    def: '1900',
    pkg: ['LODT(508)'],
  },
];
